# Generated by Django 4.2.7 on 2023-11-25 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('login', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('invitedBy', models.CharField(max_length=500)),
                ('hand_left', models.CharField(max_length=500)),
                ('hand_right', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
