# Generated by Django 4.2.7 on 2023-11-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
    ]
