# Generated by Django 4.2.7 on 2023-11-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userid_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.CharField(max_length=500)),
                ('kitoblar', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Haridlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kitoblar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
